version: '3'
services:
  beer:
    build:
      context: .
      dockerfile: Dockerfile
    image: veddev/beer:latest
    environment:
      - BUILD_ENV=dev
    ports:
      - 4200:4200
    # command: /bin/bash -c "sleep 7 && python3 app.py"
