---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beer-config
  labels:
    app: beer
data:
  ENV: DEV
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: beer
  name: beer
spec:
  replicas: 1
  strategy: {}
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beer
    spec:
      containers:
      - image: veddev/beer:latest
        name: beer-image
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: beer-config
        # env:
        #   - name: DEPLOYMENT_TIMESTAMP
        #     value: VAR_DEPLOYMENT_DATE
        ports:
        - containerPort: 4200
        resources: {}
      # imagePullSecrets:
      #   - name: azure-container-repo
      restartPolicy: Always
      # terminationGracePeriodSeconds: 20

status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: beer
  name: beer
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    protocol: TCP
    port: 80
    targetPort: 4200
  selector:
    io.kompose.service: beer
status:
  loadBalancer: {}
